/**
 * Demo seed for the scheduling system. Idempotent — re-run any time.
 * Creates two self-contained scenarios (slug/email prefix "sched-demo"):
 *   1. 1v1 knockout — two players, overlapping evenings, a generated schedule
 *      awaiting confirmation (player A confirmed, player B still to confirm).
 *   2. 2v2 knockout — two duos where the four players do NOT all overlap, plus
 *      a registered substitute whose availability unlocks slots.
 *
 * Run: npx tsx prisma/seed-scheduling.ts
 */
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { generateProposedSlots } from "../src/lib/scheduling/engine";
import { blocksToIntervals, type BlockLike } from "../src/lib/scheduling/blocks";
import { pktInstant } from "../src/lib/scheduling/time";
import type { EngineSide, SubstituteOption } from "../src/lib/scheduling/types";

const prisma = new PrismaClient();
const DEMO_PW = "bwl-demo-2026";
const pad = (n: number) => String(n).padStart(2, "0");

function pktDay(offsetDays: number) {
  const d = new Date(Date.now() + offsetDays * 86_400_000 + 5 * 3_600_000);
  const y = d.getUTCFullYear();
  const m = d.getUTCMonth() + 1;
  const day = d.getUTCDate();
  return { y, m, day, dateStr: `${y}-${pad(m)}-${pad(day)}` };
}

const DAYS = [2, 3, 4, 5, 6]; // availability window offsets from "now"
const DEADLINE = new Date(Date.now() + 21 * 86_400_000);

async function cleanup() {
  const demoT = await prisma.tournament.findMany({ where: { slug: { startsWith: "sched-demo" } }, select: { id: true } });
  const tIds = demoT.map((t) => t.id);
  if (tIds.length) await prisma.schedulingAuditEvent.deleteMany({ where: { tournamentId: { in: tIds } } });
  await prisma.tournament.deleteMany({ where: { id: { in: tIds } } });
  await prisma.team.deleteMany({ where: { slug: { startsWith: "sched-demo" } } });
  const demoP = await prisma.player.findMany({ where: { slug: { startsWith: "sched-demo" } }, select: { id: true } });
  if (demoP.length) await prisma.schedulingAuditEvent.deleteMany({ where: { playerId: { in: demoP.map((p) => p.id) } } });
  await prisma.player.deleteMany({ where: { slug: { startsWith: "sched-demo" } } });
}

let counter = 0;
async function mkPlayer(name: string, pwHash: string) {
  counter++;
  return prisma.player.create({
    data: { name, slug: `sched-demo-${counter}`, email: `sched-demo-${counter}@bwl.test`, passwordHash: pwHash },
  });
}

const periodCache = new Map<string, string>();
async function periodId(playerId: string, m: number, y: number): Promise<string> {
  const key = `${playerId}:${m}:${y}`;
  if (periodCache.has(key)) return periodCache.get(key)!;
  const p = await prisma.playerAvailabilityPeriod.upsert({
    where: { playerId_month_year: { playerId, month: m, year: y } },
    create: { playerId, month: m, year: y, status: "SUBMITTED", submittedAt: new Date() },
    update: { status: "SUBMITTED" },
  });
  periodCache.set(key, p.id);
  return p.id;
}

async function addAvailability(playerId: string, offsets: number[], startH: number, endH: number, status = "CONFIRMED") {
  for (const off of offsets) {
    const { y, m, day, dateStr } = pktDay(off);
    const pid = await periodId(playerId, m, y);
    await prisma.availabilityBlock.create({
      data: {
        periodId: pid, playerId, date: new Date(`${dateStr}T00:00:00Z`), status: status as never,
        isAllDay: false, isOvernight: false,
        startDateTime: new Date(pktInstant(y, m, day, startH, 0)), endDateTime: new Date(pktInstant(y, m, day, endH, 0)),
        privacy: "PRIVATE", source: "MANUAL",
      },
    });
  }
}

async function intervalsFor(playerId: string) {
  const blocks = await prisma.availabilityBlock.findMany({ where: { playerId } });
  const likes: BlockLike[] = blocks.map((b) => ({
    date: b.date.toISOString().slice(0, 10), startDateTime: b.startDateTime, endDateTime: b.endDateTime,
    status: b.status as BlockLike["status"], isAllDay: b.isAllDay, isOvernight: b.isOvernight,
  }));
  return blocksToIntervals(likes);
}

/** Persist an engine result to MatchSchedule + slots + PENDING confirmations. */
async function persistSchedule(matchId: string, sides: EngineSide[], substitutes: SubstituteOption[]) {
  const result = generateProposedSlots({
    sides, substitutes,
    options: {
      matchDurationMinutes: 60, preMatchBufferMinutes: 10, postMatchBufferMinutes: 10,
      windowStart: Date.now(), windowEnd: DEADLINE.getTime(), deadline: DEADLINE.getTime(), maxSlots: 6,
    },
  });
  const status = result.slots.length ? "AWAITING_CONFIRMATION" : "NO_COMMON_TIME";
  const schedule = await prisma.matchSchedule.upsert({
    where: { matchId },
    create: { matchId, schedulingStatus: status as never, schedulingMode: "PLAYER_CHOICE", autoGenerated: true, confirmationDeadline: new Date(Date.now() + 24 * 3_600_000) },
    update: { schedulingStatus: status as never },
  });
  await prisma.proposedMatchSlot.deleteMany({ where: { matchScheduleId: schedule.id } });
  let selected: string | null = null, pS: Date | null = null, pE: Date | null = null, bS: Date | null = null, bE: Date | null = null;
  for (const slot of result.slots) {
    const created = await prisma.proposedMatchSlot.create({
      data: {
        matchScheduleId: schedule.id, startDateTime: new Date(slot.kickoff), endDateTime: new Date(slot.matchEnd),
        score: slot.score, rank: slot.rank, eligibility: slot.eligibility as never,
        requiresSubstitute: slot.requiresSubstitute, isPrimary: slot.isPrimary, isBackup: slot.isBackup, scoringExplanation: slot.explanation,
      },
    });
    if (slot.isPrimary) { selected = created.id; pS = new Date(slot.kickoff); pE = new Date(slot.matchEnd); }
    if (slot.isBackup) { bS = new Date(slot.kickoff); bE = new Date(slot.matchEnd); }
  }
  await prisma.matchSchedule.update({ where: { id: schedule.id }, data: { selectedSlotId: selected, primaryStart: pS, primaryEnd: pE, backupStart: bS, backupEnd: bE } });
  // Confirmations for the base lineup.
  for (const side of sides) {
    for (const p of side.players) {
      await prisma.matchParticipantConfirmation.upsert({
        where: { matchScheduleId_playerId: { matchScheduleId: schedule.id, playerId: p.playerId } },
        create: { matchScheduleId: schedule.id, playerId: p.playerId, teamId: side.teamId, status: "PENDING" },
        update: { status: "PENDING" },
      });
    }
  }
  return { scheduleId: schedule.id, selected, slots: result.slots.length };
}

async function main() {
  console.log("🌱 Seeding scheduling demo data…");
  await cleanup();
  const pwHash = await bcrypt.hash(DEMO_PW, 10);

  // ── Scenario 1: 1v1 knockout ──
  const A = await mkPlayer("Demo Ali (1v1)", pwHash);
  const B = await mkPlayer("Demo Bilal (1v1)", pwHash);
  await addAvailability(A.id, DAYS, 20, 23, "CONFIRMED");
  await addAvailability(B.id, DAYS, 21, 23, "CONFIRMED"); // overlap 9–11pm

  const t1 = await prisma.tournament.create({
    data: { name: "Demo 1v1 Cup", slug: "sched-demo-1v1", gameCategory: "EFOOTBALL", format: "KNOCKOUT", participantType: "INDIVIDUAL", eFootballMode: "1v1", status: "DRAFT" },
  });
  await prisma.tournamentSchedulingSettings.create({ data: { tournamentId: t1.id, enabled: true, schedulingMode: "PLAYER_CHOICE", substitutesEnabled: false } });
  await prisma.tournamentPlayer.createMany({ data: [{ tournamentId: t1.id, playerId: A.id }, { tournamentId: t1.id, playerId: B.id }] });
  const m1 = await prisma.match.create({ data: { tournamentId: t1.id, round: "Final", roundNumber: 1, matchNumber: 1, homePlayerId: A.id, awayPlayerId: B.id, status: "SCHEDULED", deadline: DEADLINE } });

  const s1 = await persistSchedule(
    m1.id,
    [
      { sideId: "home", players: [{ playerId: A.id, sideId: "home", intervals: await intervalsFor(A.id) }] },
      { sideId: "away", players: [{ playerId: B.id, sideId: "away", intervals: await intervalsFor(B.id) }] },
    ],
    []
  );
  // Player A confirms the primary; B still pending → PARTIALLY_CONFIRMED.
  if (s1.selected) {
    await prisma.matchParticipantConfirmation.updateMany({ where: { matchScheduleId: s1.scheduleId, playerId: A.id }, data: { status: "CONFIRMED", proposedSlotId: s1.selected, respondedAt: new Date() } });
    await prisma.matchSchedule.update({ where: { id: s1.scheduleId }, data: { schedulingStatus: "PARTIALLY_CONFIRMED" } });
  }
  console.log(`  ✅ 1v1: ${s1.slots} slots proposed, A confirmed, B pending`);

  // ── Scenario 2: 2v2 knockout with substitute ──
  const p1 = await mkPlayer("Demo Kamran (2v2)", pwHash);
  const p2 = await mkPlayer("Demo Sana (2v2)", pwHash);
  const p3 = await mkPlayer("Demo Omar (2v2)", pwHash);
  const p4 = await mkPlayer("Demo Zoya (2v2)", pwHash); // only mornings → blocks 4-player overlap
  const sub = await mkPlayer("Demo Hasan (sub)", pwHash);
  await addAvailability(p1.id, DAYS, 20, 23, "CONFIRMED");
  await addAvailability(p2.id, DAYS, 20, 23, "CONFIRMED");
  await addAvailability(p3.id, DAYS, 21, 23, "CONFIRMED");
  await addAvailability(p4.id, DAYS, 8, 10, "CONFIRMED"); // mornings only
  await addAvailability(sub.id, DAYS, 21, 23, "CONFIRMED"); // evenings → unlocks overlap

  const mkDuo = async (name: string, slug: string, a: string, b: string, captain: string) => {
    const team = await prisma.team.create({ data: { name, slug, isDuo: true, captainId: captain } });
    await prisma.teamPlayer.createMany({ data: [{ teamId: team.id, playerId: a }, { teamId: team.id, playerId: b }] });
    return team;
  };
  const duo1 = await mkDuo("Demo Duo One", "sched-demo-duo-1", p1.id, p2.id, p1.id);
  const duo2 = await mkDuo("Demo Duo Two", "sched-demo-duo-2", p3.id, p4.id, p3.id);

  const t2 = await prisma.tournament.create({
    data: { name: "Demo 2v2 Cup", slug: "sched-demo-2v2", gameCategory: "EFOOTBALL", format: "KNOCKOUT", participantType: "TEAM", eFootballMode: "2v2", status: "DRAFT" },
  });
  await prisma.tournamentSchedulingSettings.create({ data: { tournamentId: t2.id, enabled: true, schedulingMode: "PLAYER_CHOICE", substitutesEnabled: true, captainConfirmationEnabled: true } });
  await prisma.tournamentTeam.createMany({ data: [{ tournamentId: t2.id, teamId: duo1.id }, { tournamentId: t2.id, teamId: duo2.id }] });
  await prisma.substituteRegistration.create({ data: { tournamentId: t2.id, teamId: duo2.id, playerId: sub.id, status: "APPROVED" } });
  const m2 = await prisma.match.create({ data: { tournamentId: t2.id, round: "Final", roundNumber: 1, matchNumber: 1, homeTeamId: duo1.id, awayTeamId: duo2.id, status: "SCHEDULED", deadline: DEADLINE } });

  const subOption: SubstituteOption = { sideId: "away", participant: { playerId: sub.id, sideId: "away", isSubstitute: true, intervals: await intervalsFor(sub.id) } };
  const s2 = await persistSchedule(
    m2.id,
    [
      { sideId: "home", teamId: duo1.id, players: [{ playerId: p1.id, sideId: "home", intervals: await intervalsFor(p1.id) }, { playerId: p2.id, sideId: "home", intervals: await intervalsFor(p2.id) }] },
      { sideId: "away", teamId: duo2.id, players: [{ playerId: p3.id, sideId: "away", intervals: await intervalsFor(p3.id) }, { playerId: p4.id, sideId: "away", intervals: await intervalsFor(p4.id) }] },
    ],
    [subOption]
  );
  console.log(`  ✅ 2v2: ${s2.slots} sub-based slot(s) proposed (Zoya unavailable evenings → Hasan unlocks it)`);

  console.log("\n🎉 Done. Demo logins (player portal /player/login):");
  console.log(`   sched-demo-2@bwl.test  (Demo Bilal)  — confirm the 1v1 final`);
  console.log(`   sched-demo-6@bwl.test  (Demo Kamran, captain) — activate the 2v2 substitute`);
  console.log(`   password for all: ${DEMO_PW}`);
  console.log("   Admin: /admin/scheduling → Demo 1v1 Cup / Demo 2v2 Cup");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
